chore: update charmcraft.yaml parts to use subdirectory for grafana dashboards directory
canonical/maas-charms pull request #257
Opened 2024-10-16 21:57 UTC by wyattrees

This PR requires https://github.com/canonical/maas-grafana-dashboards/pull/1 to be merged, which splits the dashboards into directories

2024-10-21 15:16 UTC, skatsaounis approved these changes
LGTM with the suggestions. Please take a look for any typo before applying them :)

2024-10-21 15:16 UTC, skatsaounis commented on maas-region/charmcraft.yaml
> +      maas_stats.json: src/grafana_dashboards/maas_stats.json
```suggestion
      maas_stats.json: src/grafana_dashboards/maas/maas_stats.json
```

2024-10-21 15:16 UTC, skatsaounis commented on maas-region/charmcraft.yaml
>        - src/grafana_dashboards/maas_stats.json
```suggestion
      - src/grafana_dashboards/maas/maas_stats.json
```

2024-10-22 07:11 UTC, skatsaounis requested changes
My initial suggestion were wrong, so please ignore. However, I think that we should leave organize intact to be able to get all the JSON dashboard files that we currently have in the repo and also those that we will add in the future. To do that, a change to prime is also needed as suggested.

More info:
- https://canonical-craft-parts.readthedocs-hosted.com/en/latest/common/craft-parts/reference/part_properties.html#organize
- https://canonical-craft-parts.readthedocs-hosted.com/en/latest/common/craft-parts/reference/part_properties.html#prime
- https://canonical-craft-parts.readthedocs-hosted.com/en/latest/common/craft-parts/explanation/filesets.html#filesets-specifying-paths

2024-10-22 07:11 UTC, skatsaounis commented on maas-region/charmcraft.yaml
> +      maas_stats.json: src/grafana_dashboards/maas_stats.json
```suggestion
      "*": src/grafana_dashboards/
```

2024-10-22 07:11 UTC, skatsaounis commented on maas-region/charmcraft.yaml
>        - src/grafana_dashboards/maas_stats.json
```suggestion
      - src/grafana_dashboards/*
```

2024-10-22 13:50 UTC, alema-r approved these changes
LGTM

2024-10-22 13:58 UTC, skatsaounis approved these changes
LGTM +1

2024-10-22 14:02 UTC, merged